// Code Generated by Sidekick is for learning and experimentation purposes only.

import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { AI_TOOLS } from '../data/tools'
import ToolCard from './ToolCard'

const questions = [
  {
    id: 1,
    text: "What's your primary use case?",
    options: [
      { value: 'research', label: 'Research & Analysis', tags: ['research', 'analysis'] },
      { value: 'content', label: 'Content Creation & Writing', tags: ['content', 'writing'] },
      { value: 'coding', label: 'Coding & Development', tags: ['coding', 'development'] },
      { value: 'data', label: 'Data Analysis & Visualization', tags: ['data', 'analytics'] },
      { value: 'creative', label: 'Creative Design & Media', tags: ['creative', 'design'] },
      { value: 'automation', label: 'Workflow Automation', tags: ['automation', 'productivity'] },
    ]
  },
  {
    id: 2,
    text: "What's your technical experience level?",
    options: [
      { value: 'beginner', label: 'Beginner - New to AI tools', tags: ['beginner'] },
      { value: 'intermediate', label: 'Intermediate - Some experience', tags: ['intermediate'] },
      { value: 'advanced', label: 'Advanced - Very comfortable', tags: ['advanced'] },
      { value: 'expert', label: 'Expert - Power user', tags: ['expert'] },
    ]
  },
  {
    id: 3,
    text: "What type of output do you need most?",
    options: [
      { value: 'text', label: 'Text & Documents', tags: ['text', 'writing'] },
      { value: 'code', label: 'Code & Scripts', tags: ['coding', 'development'] },
      { value: 'images', label: 'Images & Graphics', tags: ['image', 'creative'] },
      { value: 'data', label: 'Data & Charts', tags: ['data', 'analytics'] },
      { value: 'mixed', label: 'Mix of everything', tags: ['versatile'] },
    ]
  },
  {
    id: 4,
    text: "How often will you use this tool?",
    options: [
      { value: 'daily', label: 'Daily - Core part of my workflow', tags: ['frequent'] },
      { value: 'weekly', label: 'Weekly - Regular use', tags: ['regular'] },
      { value: 'monthly', label: 'Monthly - Occasional projects', tags: ['occasional'] },
      { value: 'rarely', label: 'Rarely - Specific needs only', tags: ['occasional'] },
    ]
  },
  {
    id: 5,
    text: "Are you working solo or with a team?",
    options: [
      { value: 'solo', label: 'Solo - Just me', tags: ['individual'] },
      { value: 'small', label: 'Small team (2-5 people)', tags: ['collaboration'] },
      { value: 'large', label: 'Large team (6+ people)', tags: ['collaboration', 'enterprise'] },
      { value: 'both', label: 'Both solo and team work', tags: ['versatile'] },
    ]
  },
  {
    id: 6,
    text: "What's your budget?",
    options: [
      { value: 'free', label: 'Free only', tags: ['free'] },
      { value: 'low', label: 'Under $20/month', tags: ['affordable'] },
      { value: 'medium', label: '$20-$50/month', tags: ['moderate'] },
      { value: 'high', label: '$50+/month', tags: ['premium'] },
      { value: 'flexible', label: 'Flexible - willing to pay for value', tags: ['flexible'] },
    ]
  },
  {
    id: 7,
    text: "Do you need integration with other tools?",
    options: [
      { value: 'none', label: 'No - standalone is fine', tags: ['standalone'] },
      { value: 'basic', label: 'Basic - export/import files', tags: ['basic-integration'] },
      { value: 'advanced', label: 'Advanced - API & workflows', tags: ['integration', 'api'] },
      { value: 'ecosystem', label: 'Full ecosystem integration', tags: ['integration', 'enterprise'] },
    ]
  },
  {
    id: 8,
    text: "What's most important to you?",
    options: [
      { value: 'speed', label: 'Speed & responsiveness', tags: ['performance'] },
      { value: 'quality', label: 'Output quality', tags: ['quality'] },
      { value: 'ease', label: 'Ease of use', tags: ['beginner', 'usability'] },
      { value: 'features', label: 'Feature breadth', tags: ['versatile'] },
      { value: 'support', label: 'Support & documentation', tags: ['support'] },
    ]
  },
  {
    id: 9,
    text: "Do you have specific security/compliance needs?",
    options: [
      { value: 'none', label: 'No special requirements', tags: [] },
      { value: 'basic', label: 'Basic privacy concerns', tags: ['privacy'] },
      { value: 'enterprise', label: 'Enterprise security required', tags: ['enterprise', 'security'] },
      { value: 'regulated', label: 'Regulated industry compliance', tags: ['compliance', 'security'] },
    ]
  },
  {
    id: 10,
    text: "What's your learning preference?",
    options: [
      { value: 'dive-in', label: 'Dive in - figure it out myself', tags: ['self-service'] },
      { value: 'tutorials', label: 'Need good tutorials & guides', tags: ['support', 'beginner'] },
      { value: 'community', label: 'Active community support', tags: ['community'] },
      { value: 'training', label: 'Formal training & certification', tags: ['enterprise', 'support'] },
    ]
  },
]

export default function Quiz() {
  const [currentQuestion, setCurrentQuestion] = useState(0)
  const [answers, setAnswers] = useState<Record<number, string>>({})
  const [showResults, setShowResults] = useState(false)
  const [recommendations, setRecommendations] = useState<typeof AI_TOOLS>([])

  const handleAnswer = (value: string) => {
    setAnswers({ ...answers, [questions[currentQuestion].id]: value })
  }

  const handleNext = () => {
    if (currentQuestion < questions.length - 1) {
      setCurrentQuestion(currentQuestion + 1)
    } else {
      const recs = calculateRecommendations(answers)
      setRecommendations(recs)
      setShowResults(true)
    }
  }

  const handleBack = () => {
    if (currentQuestion > 0) {
      setCurrentQuestion(currentQuestion - 1)
    }
  }

  const handleRestart = () => {
    setCurrentQuestion(0)
    setAnswers({})
    setShowResults(false)
    setRecommendations([])
  }

  const calculateRecommendations = (answers: Record<number, string>) => {
    const allTags: string[] = []
    
    // Collect all tags from answers
    questions.forEach(q => {
      const answer = answers[q.id]
      if (answer) {
        const option = q.options.find(opt => opt.value === answer)
        if (option) {
          allTags.push(...option.tags)
        }
      }
    })

    // Score each tool
    const scoredTools = AI_TOOLS.map(tool => {
      let score = 0
      
      // Category matching (highest weight)
      if (allTags.includes(tool.category.toLowerCase())) {
        score += 30
      }
      
      // Use case matching
      tool.useCases.forEach(useCase => {
        if (allTags.some(tag => useCase.toLowerCase().includes(tag))) {
          score += 15
        }
      })
      
      // Strengths matching (was "features")
      tool.strengths.forEach(strength => {
        if (allTags.some(tag => strength.toLowerCase().includes(tag))) {
          score += 10
        }
      })
      
      // Best for matching
      tool.bestFor.forEach(best => {
        if (allTags.some(tag => best.toLowerCase().includes(tag))) {
          score += 12
        }
      })
      
      // Budget preference (softer filter)
      const budgetAnswer = answers[6] // Question 6 is budget
      if (budgetAnswer) {
        if (budgetAnswer === 'free' && tool.pricing.toLowerCase().includes('free')) {
          score += 25
        } else if (budgetAnswer === 'flexible') {
          score += 5 // Small bonus for any tool if budget is flexible
        } else if (!tool.pricing.toLowerCase().includes('free') && budgetAnswer !== 'free') {
          score += 10 // Bonus if they're willing to pay and it's a paid tool
        }
      }

      return { tool, score }
    })

    // Sort by score
    const sorted = scoredTools.sort((a, b) => b.score - a.score)
    
    // FALLBACK LOGIC: If top score is 0 or very low, show popular versatile tools
    if (sorted[0].score < 20) {
      console.log('Low scores detected, using fallback recommendations')
      const fallbackTools = AI_TOOLS.filter(tool => 
        ['ChatGPT', 'Claude', 'GitHub Copilot', 'Grammarly', 'QuickBooks Online'].includes(tool.name)
      )
      return fallbackTools.slice(0, 5)
    }
    
    // Return top 5, but ensure we ALWAYS have at least 3 results
    const topResults = sorted.slice(0, 5).map(s => s.tool)
    
    if (topResults.length < 3) {
      // Add popular tools to fill to at least 3
      const fillers = AI_TOOLS.filter(tool => 
        !topResults.includes(tool) && 
        ['ChatGPT', 'Claude', 'GitHub Copilot'].includes(tool.name)
      )
      return [...topResults, ...fillers].slice(0, 5)
    }
    
    return topResults
  }

  const progress = ((currentQuestion + 1) / questions.length) * 100
  const currentQ = questions[currentQuestion]
  const hasAnswer = answers[currentQ.id] !== undefined

  if (showResults) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-purple-50 via-blue-50 to-cyan-50 py-12 px-4">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center mb-12"
          >
            <div className="inline-flex items-center gap-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white px-6 py-3 rounded-full mb-6">
              <span className="text-xl">✨</span>
              <span className="font-semibold">Your Personalized Recommendations</span>
            </div>
            <h2 className="text-3xl font-bold text-gray-900 mb-4">
              Perfect Matches for Your Needs
            </h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              Based on your answers, here are the AI tools that best fit your requirements
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
            {recommendations.map((tool, index) => (
              <motion.div
                key={tool.name}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
              >
                <ToolCard tool={tool} featured={index === 0} />
              </motion.div>
            ))}
          </div>

          <div className="text-center">
            <button
              onClick={handleRestart}
              className="bg-gradient-to-r from-purple-600 to-blue-600 text-white px-8 py-3 rounded-lg font-semibold hover:shadow-lg transition-shadow"
            >
              Start Over
            </button>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-blue-50 to-cyan-50 py-12 px-4">
      <div className="max-w-3xl mx-auto">
        {/* Progress Bar */}
        <div className="mb-8">
          <div className="flex justify-between items-center mb-2">
            <span className="text-sm font-medium text-gray-600">
              Question {currentQuestion + 1} of {questions.length}
            </span>
            <span className="text-sm font-medium text-purple-600">
              {Math.round(progress)}% Complete
            </span>
          </div>
          <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
            <motion.div
              className="h-full bg-gradient-to-r from-purple-600 to-blue-600"
              initial={{ width: 0 }}
              animate={{ width: `${progress}%` }}
              transition={{ duration: 0.3 }}
            />
          </div>
        </div>

        {/* Question Card */}
        <AnimatePresence mode="wait">
          <motion.div
            key={currentQuestion}
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            className="bg-white rounded-2xl shadow-xl p-8 mb-6"
          >
            <h2 className="text-2xl font-bold text-gray-900 mb-6">
              {currentQ.text}
            </h2>

            <div className="space-y-3">
              {currentQ.options.map((option) => (
                <button
                  key={option.value}
                  onClick={() => handleAnswer(option.value)}
                  className={`w-full text-left p-4 rounded-lg border-2 transition-all ${
                    answers[currentQ.id] === option.value
                      ? 'border-purple-600 bg-purple-50'
                      : 'border-gray-200 hover:border-purple-300 hover:bg-gray-50'
                  }`}
                >
                  <span className="font-medium text-gray-900">{option.label}</span>
                </button>
              ))}
            </div>
          </motion.div>
        </AnimatePresence>

        {/* Navigation Buttons */}
        <div className="flex justify-between items-center">
          <button
            onClick={handleBack}
            disabled={currentQuestion === 0}
            className="flex items-center gap-2 px-6 py-3 rounded-lg font-semibold transition-all disabled:opacity-50 disabled:cursor-not-allowed text-gray-700 hover:bg-gray-100"
          >
            <span>←</span>
            Back
          </button>

          <button
            onClick={handleNext}
            disabled={!hasAnswer}
            className="flex items-center gap-2 px-6 py-3 rounded-lg font-semibold transition-all disabled:opacity-50 disabled:cursor-not-allowed bg-gradient-to-r from-purple-600 to-blue-600 text-white hover:shadow-lg"
          >
            {currentQuestion === questions.length - 1 ? 'See Results' : 'Next'}
            <span>→</span>
          </button>
        </div>
      </div>
    </div>
  )
}
