// Code Generated by Sidekick is for learning and experimentation purposes only.
// src/utils/scoringEngine.ts

import { AI_TOOLS } from '@/data/tools'

// ==================== TYPES ====================

export interface ScoredTool {
  id: string
  name: string
  description: string
  category: string
  pricing: string
  link: string
  strengths: string[]
  useCases: string[]
  bestFor: string[]
  
  // Scoring details
  score: number
  roleAlignment: number
  taskAlignment: number
  budgetAlignment: number
  matchReasons: string[]
  confidenceLevel: 'high' | 'medium' | 'low'
}

// ==================== BUDGET MAPPING ====================

const BUDGET_TIERS: Record<string, string[]> = {
  free: ['free'],
  minimal: ['free', 'low'],
  low: ['free', 'low'],
  medium: ['free', 'low', 'mid'],
  high: ['free', 'low', 'mid', 'high'],
  enterprise: ['free', 'low', 'mid', 'high', 'enterprise'],
  flexible: ['free', 'low', 'mid', 'high', 'enterprise']
}

// ==================== MAIN RECOMMENDATION FUNCTION ====================

export function getTopRecommendations(
  userProfile: Record<string, string>,
  maxResults: number = 20
): ScoredTool[] {
  // Score all tools
  const scoredTools = AI_TOOLS.map(tool => scoreToolForUser(tool, userProfile))
    .filter(scored => scored.score > 0) // Remove zero-scored tools
    .sort((a, b) => b.score - a.score) // Sort by score descending

  return scoredTools.slice(0, maxResults)
}

// ==================== SCORING ALGORITHM ====================

function scoreToolForUser(tool: any, profile: Record<string, string>): ScoredTool {
  const role = profile.role || ''
  const painPoint = profile[`${role}_pain_point`] || ''
  const primaryTask = profile[`${role}_primary_task`] || ''
  const budget = profile.budget || 'flexible'
  const techComfort = profile.tech_comfort || 'comfortable'

  // Collect all user pain points
  const userPainPoints = [primaryTask, painPoint].filter(Boolean)

  // 1. ROLE MATCHING (50% weight) - MOST CRITICAL
  const roleScore = calculateRoleScore(tool, role)
  if (roleScore === -1) {
    // Hard exclusion - tool not recommended for this role
    return createZeroScoredTool(tool)
  }

  // 2. TASK MATCHING (40% weight)
  const taskScore = calculateTaskScore(tool, userPainPoints)
  if (taskScore === 0) {
    // Tool doesn't solve their problems
    return createZeroScoredTool(tool)
  }

  // 3. BUDGET FILTER (gate, not score)
  if (!isBudgetCompatible(tool, budget)) {
    return createZeroScoredTool(tool)
  }

  // 4. TECH LEVEL (10% weight)
  const techScore = calculateTechScore(tool, techComfort)

  // Calculate weighted total (out of 100)
  let totalScore = (roleScore * 0.5) + (taskScore * 0.4) + (techScore * 0.1)

  // Apply tool-specific priority multiplier
  const priority = tool.recommendPriority || 5
  totalScore *= (priority / 10)

  // Industry bonus (small boost)
  if (tool.industries.includes(profile.industry) || tool.industries.includes('all')) {
    totalScore *= 1.1
  }

  // Generate match reasons
  const matchReasons = generateMatchReasons(tool, profile, userPainPoints)

  // Determine confidence level
  const confidenceLevel = getConfidenceLevel(totalScore, matchReasons.length)

  return {
    ...tool,
    score: Math.round(totalScore),
    roleAlignment: Math.round(roleScore * 0.15), // Scale to 0-15 for UI
    taskAlignment: Math.round(taskScore * 0.16), // Scale to 0-16 for UI
    budgetAlignment: 9, // Full budget alignment if it passed the filter
    matchReasons,
    confidenceLevel
  }
}

// ==================== ROLE SCORING ====================

function calculateRoleScore(tool: any, userRole: string): number {
  const roleMatch = tool.roleMatch

  if (!roleMatch) {
    // Legacy tool without roleMatch - use old logic
    if (tool.roles.includes(userRole) || tool.roles.includes('all')) {
      return 75 // Moderate match
    }
    return 50 // Weak match
  }

  // Check hard exclusion
  if (roleMatch.exclude?.includes(userRole)) {
    return -1 // Signal exclusion
  }

  // Primary match (perfect for this role)
  if (roleMatch.primary.includes(userRole) || roleMatch.primary.includes('all')) {
    return 100
  }

  // Secondary match (useful but not primary)
  if (roleMatch.secondary.includes(userRole) || roleMatch.secondary.includes('all')) {
    return 50
  }

  // No specific match
  return 10
}

// ==================== TASK SCORING ====================

function calculateTaskScore(tool: any, userPainPoints: string[]): number {
  const taskMatch = tool.taskMatch

  if (!taskMatch) {
    // Legacy tool - check use cases
    const matches = tool.useCases.filter((uc: string) => 
      userPainPoints.some(pp => uc.includes(pp) || pp.includes(uc))
    ).length
    return Math.min(matches * 20, 100)
  }

  // Check if tool explicitly CANNOT solve their problems
  if (taskMatch.noMatch) {
    const hasNoMatch = taskMatch.noMatch.some((task: string) => 
      userPainPoints.includes(task)
    )
    if (hasNoMatch) return 0
  }

  let score = 0

  // Strong matches (20 points each)
  const strongMatches = taskMatch.strongMatch.filter((task: string) => 
    userPainPoints.includes(task)
  ).length
  score += strongMatches * 20

  // Weak matches (5 points each)
  if (taskMatch.weakMatch) {
    const weakMatches = taskMatch.weakMatch.filter((task: string) => 
      userPainPoints.includes(task)
    ).length
    score += weakMatches * 5
  }

  return Math.min(score, 100)
}

// ==================== BUDGET COMPATIBILITY ====================

function isBudgetCompatible(tool: any, userBudget: string): boolean {
  if (userBudget === 'flexible') return true

  const allowedTiers = BUDGET_TIERS[userBudget]
  if (!allowedTiers) return true

  const toolTier = inferPricingTier(tool.pricing)
  return allowedTiers.includes(toolTier)
}

function inferPricingTier(pricingString: string): string {
  const lower = pricingString.toLowerCase()
  
  if (lower.includes('free') || lower === '$0') return 'free'
  if (lower.includes('enterprise') || lower.includes('contact')) return 'enterprise'
  
  const match = pricingString.match(/\$(\d+)/)
  if (!match) return 'mid'
  
  const price = parseInt(match[1])
  if (price === 0) return 'free'
  if (price <= 25) return 'low'
  if (price <= 100) return 'mid'
  if (price <= 500) return 'high'
  return 'enterprise'
}

// ==================== TECH SCORING ====================

function calculateTechScore(tool: any, techComfort: string): number {
  const comfortLevels: Record<string, number> = {
    beginner: 1,
    moderate: 2,
    comfortable: 3,
    expert: 5
  }

  const userLevel = comfortLevels[techComfort] || 3
  const toolLevel = estimateToolTechLevel(tool)

  // Perfect match
  if (userLevel === toolLevel) return 100

  // Close match
  if (Math.abs(userLevel - toolLevel) === 1) return 75

  // Within 2 levels
  if (Math.abs(userLevel - toolLevel) === 2) return 50

  // Tool too complex
  if (toolLevel > userLevel) return 25

  // Tool too simple
  return 60
}

function estimateToolTechLevel(tool: any): number {
  const category = tool.category.toLowerCase()
  
  if (category.includes('code') || category.includes('developer')) return 4
  if (category.includes('automation') || category.includes('api')) return 3
  if (category.includes('writing') || category.includes('chat') || category.includes('assistant')) return 1
  if (category.includes('data') || category.includes('analytics')) return 3
  if (category.includes('spreadsheet')) return 2
  
  return 2
}

// ==================== MATCH REASONS ====================

function generateMatchReasons(
  tool: any,
  profile: Record<string, string>,
  userPainPoints: string[]
): string[] {
  const reasons: string[] = []

  // Role-based reason
  const roleMatch = tool.roleMatch
  if (roleMatch?.primary.includes(profile.role)) {
    reasons.push(`Built specifically for ${formatRole(profile.role)} professionals`)
  } else if (roleMatch?.primary.includes('all')) {
    reasons.push('Versatile tool useful for any role')
  } else if (tool.roles?.includes(profile.role)) {
    reasons.push(`Designed for ${formatRole(profile.role)} workflows`)
  }

  // Task-based reasons
  const taskMatch = tool.taskMatch
  if (taskMatch?.strongMatch) {
    const matches = taskMatch.strongMatch.filter((task: string) => 
      userPainPoints.includes(task)
    )
    if (matches.length > 0) {
      reasons.push(`Directly solves: ${formatPainPoints(matches)}`)
    }
  }

  // Use case reasons (fallback)
  if (reasons.length < 2) {
    const useCaseMatches = tool.useCases.filter((uc: string) =>
      userPainPoints.some(pp => uc.includes(pp.replace(/_/g, ' ')))
    )
    if (useCaseMatches.length > 0) {
      reasons.push(`Strong for: ${useCaseMatches.slice(0, 2).join(', ').replace(/_/g, ' ')}`)
    }
  }

  // Budget reason
  if (profile.budget && tool.pricing.toLowerCase().includes('free')) {
    reasons.push('Free tier available')
  }

  // Strength-based reason
  if (tool.strengths.length > 0) {
    reasons.push(`Key strength: ${tool.strengths[0]}`)
  }

  return reasons.slice(0, 5)
}

// ==================== CONFIDENCE LEVEL ====================

function getConfidenceLevel(score: number, reasonCount: number): 'high' | 'medium' | 'low' {
  if (score >= 70 && reasonCount >= 3) return 'high'
  if (score >= 50 && reasonCount >= 2) return 'medium'
  return 'low'
}

// ==================== HELPERS ====================

function createZeroScoredTool(tool: any): ScoredTool {
  return {
    ...tool,
    score: 0,
    roleAlignment: 0,
    taskAlignment: 0,
    budgetAlignment: 0,
    matchReasons: [],
    confidenceLevel: 'low'
  }
}

function formatRole(role: string): string {
  const roleMap: Record<string, string> = {
    accounting: 'accounting',
    financial_analysis: 'financial analyst',
    software_dev: 'software developer',
    marketer: 'marketing',
    consultant: 'consulting',
    attorney: 'legal',
    sales_rep: 'sales',
    data_scientist: 'data science'
  }
  return roleMap[role] || role.replace(/_/g, ' ')
}

function formatPainPoints(points: string[]): string {
  const pointMap: Record<string, string> = {
    excel_complex: 'complex Excel formulas',
    manual_reconciliation: 'manual reconciliation',
    reconciliations: 'account reconciliations',
    financial_statements: 'financial statement preparation',
    bookkeeping: 'bookkeeping tasks',
    content_creation: 'content creation',
    email_writing: 'email writing',
    coding: 'coding tasks',
    data_analysis: 'data analysis'
  }
  
  return points
    .map(p => pointMap[p] || p.replace(/_/g, ' '))
    .slice(0, 2)
    .join(', ')
}
