// Code Generated by Sidekick is for learning and experimentation purposes only.
export interface AISolution {
  id: string;
  name: string;
  description: string;
  category: string[];
  industries: string[];
  useCases: string[];
  
  // NEW: Sophisticated matching
  roleRelevance: {
    // Primary roles this tool is built for (high match score)
    primary: string[];
    // Secondary roles that can benefit (medium match score)
    secondary: string[];
    // Roles this tool is NOT good for (exclude from recommendations)
    notRecommendedFor?: string[];
  };
  
  taskMatch: {
    // Specific pain points this solves (from questionFlows.ts)
    solves: string[];
    // Tasks this tool is NOT suited for
    doesNotSolve?: string[];
  };
  
  pricing: {
    tier: 'free' | 'low' | 'mid' | 'high' | 'enterprise';
    range: string;
    model: string;
  };
  techLevel: number; // 1-5, 1 = easiest
  companySize: string[];
  integrations: string[];
  pros: string[];
  cons: string[];
  affiliateLink: string;
  bestFor: string;
  
  // NEW: Priority scoring for better recommendations
  recommendationPriority: number; // 1-10, higher = better fit for core use case
}

export const aiSolutions: AISolution[] = [
  // ==================== ACCOUNTING & FINANCE SOLUTIONS ====================
  {
    id: 'excel-gpt',
    name: 'Excel Formula Bot / GPTExcel',
    description: 'AI that generates Excel formulas, explains complex formulas, and helps build spreadsheet models from plain English',
    category: ['Accounting', 'Finance', 'Productivity'],
    industries: ['accounting', 'finance', 'consulting', 'all'],
    useCases: ['excel-formulas', 'financial-modeling', 'data-analysis', 'accounting'],
    roleRelevance: {
      primary: ['accounting', 'financial_analysis', 'analyst', 'consultant'],
      secondary: ['operations', 'entrepreneur', 'manager'],
      notRecommendedFor: ['designer', 'content_creator', 'video_editor']
    },
    taskMatch: {
      solves: ['excel_complex', 'complex_models', 'financial_modeling', 'data_analysis', 'automation'],
      doesNotSolve: ['content_creation', 'design', 'video_editing']
    },
    pricing: {
      tier: 'low',
      range: '$7-10/month',
      model: 'Subscription'
    },
    techLevel: 1,
    companySize: ['solo', 'small', 'medium', 'large'],
    integrations: ['Excel', 'Google Sheets', 'Browser extension'],
    pros: [
      'Dramatically speeds up formula writing',
      'Explains existing complex formulas',
      'Helps with VBA and macros',
      'Works in both Excel and Google Sheets',
      'Perfect for accountants and analysts'
    ],
    cons: [
      'Requires Excel knowledge to verify outputs',
      'May need tweaking for edge cases',
      'Limited to spreadsheet tasks'
    ],
    affiliateLink: '#',
    bestFor: 'Accountants and analysts who live in Excel and need formula help',
    recommendationPriority: 10
  },
  {
    id: 'quickbooks-ai',
    name: 'QuickBooks AI Assistant',
    description: 'AI-powered bookkeeping and financial management with automated categorization and insights',
    category: ['Accounting', 'Finance'],
    industries: ['accounting', 'retail', 'services', 'consulting'],
    useCases: ['bookkeeping', 'invoicing', 'expense-tracking', 'financial-reporting'],
    roleRelevance: {
      primary: ['accounting', 'bookkeeper', 'entrepreneur'],
      secondary: ['financial_analysis', 'operations'],
      notRecommendedFor: ['developer', 'designer', 'marketer']
    },
    taskMatch: {
      solves: ['bookkeeping', 'manual_reconciliation', 'invoicing', 'financial_statements', 'period_close'],
      doesNotSolve: ['marketing', 'design', 'coding']
    },
    pricing: {
      tier: 'mid',
      range: '$30-200/month',
      model: 'Subscription per user'
    },
    techLevel: 2,
    companySize: ['solo', 'small', 'medium'],
    integrations: ['PayPal', 'Stripe', 'Bank feeds', 'Excel'],
    pros: [
      'Industry standard with AI enhancements',
      'Automated transaction categorization',
      'Easy bank reconciliation',
      'Mobile app included'
    ],
    cons: [
      'Can be complex for total beginners',
      'Additional fees for payroll',
      'Learning curve for advanced features'
    ],
    affiliateLink: '#',
    bestFor: 'Small businesses needing comprehensive accounting with AI automation',
    recommendationPriority: 9
  },
  {
    id: 'dext',
    name: 'Dext (formerly Receipt Bank)',
    description: 'AI document processing for receipts, invoices, and financial documents',
    category: ['Accounting', 'Document Processing'],
    industries: ['accounting', 'consulting', 'services'],
    useCases: ['document-processing', 'expense-tracking', 'bookkeeping'],
    roleRelevance: {
      primary: ['accounting', 'bookkeeper', 'financial_analysis'],
      secondary: ['operations', 'entrepreneur'],
      notRecommendedFor: ['developer', 'designer', 'marketer', 'content_creator']
    },
    taskMatch: {
      solves: ['finding_documentation', 'document_processing', 'data_entry', 'manual_reconciliation'],
      doesNotSolve: ['content_creation', 'design', 'marketing']
    },
    pricing: {
      tier: 'mid',
      range: '$10-50/month',
      model: 'Per user subscription'
    },
    techLevel: 1,
    companySize: ['solo', 'small', 'medium'],
    integrations: ['QuickBooks', 'Xero', 'Sage', 'Google Drive'],
    pros: [
      'Incredibly accurate OCR',
      'Mobile receipt capture',
      'Automatic data extraction',
      'Integrates with major accounting software'
    ],
    cons: [
      'Requires accounting software integration',
      'Limited standalone functionality',
      'Per-document costs can add up'
    ],
    affiliateLink: '#',
    bestFor: 'Businesses drowning in paper receipts and invoices',
    recommendationPriority: 9
  },
  {
    id: 'xero',
    name: 'Xero AI',
    description: 'Cloud accounting platform with AI-powered bank reconciliation and cash flow forecasting',
    category: ['Accounting', 'Finance'],
    industries: ['accounting', 'retail', 'services', 'consulting'],
    useCases: ['bookkeeping', 'invoicing', 'financial-reporting', 'inventory'],
    roleRelevance: {
      primary: ['accounting', 'bookkeeper', 'entrepreneur'],
      secondary: ['financial_analysis', 'operations'],
      notRecommendedFor: ['developer', 'designer', 'marketer']
    },
    taskMatch: {
      solves: ['bookkeeping', 'manual_reconciliation', 'financial_statements', 'period_close'],
      doesNotSolve: ['marketing', 'design', 'coding']
    },
    pricing: {
      tier: 'mid',
      range: '$13-70/month',
      model: 'Tiered subscription'
    },
    techLevel: 2,
    companySize: ['solo', 'small', 'medium'],
    integrations: ['Stripe', 'PayPal', 'Shopify', '1000+ apps'],
    pros: [
      'Beautiful, intuitive interface',
      'Strong app marketplace',
      'Excellent mobile experience',
      'Smart bank reconciliation'
    ],
    cons: [
      'Payroll costs extra',
      'Limited US-specific features vs QuickBooks',
      'Can get pricey with add-ons'
    ],
    affiliateLink: '#',
    bestFor: 'Modern businesses wanting cloud-first accounting',
    recommendationPriority: 9
  },
  {
    id: 'docsumo',
    name: 'Docsumo',
    description: 'AI-powered document data extraction for invoices, receipts, and forms',
    category: ['Document Processing', 'Automation'],
    industries: ['accounting', 'legal', 'healthcare', 'finance'],
    useCases: ['document-processing', 'data-entry', 'invoice-processing'],
    roleRelevance: {
      primary: ['accounting', 'operations', 'financial_analysis'],
      secondary: ['paralegal', 'compliance'],
      notRecommendedFor: ['designer', 'marketer', 'content_creator']
    },
    taskMatch: {
      solves: ['document_processing', 'data_entry', 'finding_documentation', 'automation'],
      doesNotSolve: ['content_creation', 'design', 'marketing']
    },
    pricing: {
      tier: 'mid',
      range: '$500-2000/month',
      model: 'Based on document volume'
    },
    techLevel: 3,
    companySize: ['small', 'medium', 'large'],
    integrations: ['API', 'QuickBooks', 'Zapier', 'Custom integrations'],
    pros: [
      'High accuracy extraction',
      'Custom document types',
      'API for developers',
      'Bulk processing'
    ],
    cons: [
      'Requires technical setup',
      'Pricey for small volumes',
      'Overkill for simple needs'
    ],
    affiliateLink: '#',
    bestFor: 'Medium-sized firms processing hundreds of documents monthly',
    recommendationPriority: 8
  },

  // ==================== GENERAL PURPOSE AI (STRATEGIC PLACEMENT) ====================
  {
    id: 'chatgpt-plus',
    name: 'ChatGPT Plus',
    description: 'General-purpose AI assistant for writing, analysis, coding, and problem-solving',
    category: ['General AI', 'Content Creation'],
    industries: ['all'],
    useCases: ['content-creation', 'customer-service', 'research', 'data-analysis', 'excel-help'],
    roleRelevance: {
      primary: ['all'], // Everyone can benefit
      secondary: [],
      notRecommendedFor: [] // No one excluded
    },
    taskMatch: {
      solves: [
        'excel_complex', 'research', 'data_analysis', 'report_writing', 'client_updates',
        'content_creation', 'email_writing', 'brainstorming', 'documentation'
      ],
      doesNotSolve: ['automated_bookkeeping', 'invoice_processing'] // Can't replace specialized tools
    },
    pricing: {
      tier: 'low',
      range: '$20/month',
      model: 'Per user subscription'
    },
    techLevel: 1,
    companySize: ['solo', 'small', 'medium', 'large'],
    integrations: ['Browser plugins', 'API available'],
    pros: [
      'Incredibly versatile',
      'Low cost',
      'Easy to start using',
      'Constantly improving',
      'Great for Excel formulas and financial analysis'
    ],
    cons: [
      'Generic, not industry-specific',
      'Requires prompting skills',
      'No native integrations',
      'Can make mistakes'
    ],
    affiliateLink: '#',
    bestFor: 'Anyone needing a flexible AI assistant for various tasks',
    recommendationPriority: 8
  },
  {
    id: 'claude-pro',
    name: 'Claude Pro',
    description: 'Advanced AI assistant with longer conversations, file uploads, and priority access',
    category: ['General AI'],
    industries: ['all'],
    useCases: ['content-creation', 'data-analysis', 'research', 'coding', 'document-review'],
    roleRelevance: {
      primary: ['all'],
      secondary: [],
      notRecommendedFor: []
    },
    taskMatch: {
      solves: [
        'excel_complex', 'data_analysis', 'research', 'document_review', 'report_writing',
        'variance_analysis', 'financial_modeling', 'code_generation'
      ],
      doesNotSolve: ['automated_bookkeeping', 'invoice_processing']
    },
    pricing: {
      tier: 'low',
      range: '$20/month',
      model: 'Per user subscription'
    },
    techLevel: 1,
    companySize: ['solo', 'small', 'medium', 'large'],
    integrations: ['API available for developers'],
    pros: [
      'Excellent for analysis and reasoning',
      'Can process documents and images',
      'More nuanced than ChatGPT',
      'Great for research tasks',
      'Strong with financial data analysis'
    ],
    cons: [
      'Less well-known than ChatGPT',
      'No plugin ecosystem',
      'Occasional usage limits'
    ],
    affiliateLink: '#',
    bestFor: 'Professionals needing thoughtful AI analysis and document review',
    recommendationPriority: 8
  },

  // ==================== WRITING & COMMUNICATION (LIMITED FOR ACCOUNTING) ====================
  {
    id: 'grammarly-business',
    name: 'Grammarly Business',
    description: 'AI writing assistant that improves grammar, tone, and clarity across all communications',
    category: ['Writing', 'Communication'],
    industries: ['all'],
    useCases: ['content-creation', 'email-writing', 'documentation', 'client-communication'],
    roleRelevance: {
      primary: ['content_creator', 'marketer', 'attorney', 'consultant', 'executive'],
      secondary: ['all'], // Can benefit as secondary tool
      notRecommendedFor: [] // But low priority for technical roles
    },
    taskMatch: {
      solves: ['report_formatting', 'client_updates', 'email_writing', 'documentation', 'professional_communication'],
      doesNotSolve: [
        'reconciliations', 'journal_entries', 'financial_statements', 'excel_complex',
        'data_analysis', 'bookkeeping', 'coding'
      ]
    },
    pricing: {
      tier: 'mid',
      range: '$15-30/user/month',
      model: 'Per user subscription'
    },
    techLevel: 1,
    companySize: ['solo', 'small', 'medium', 'large'],
    integrations: ['Email', 'Google Docs', 'Slack', 'Microsoft Office'],
    pros: [
      'Works everywhere you write',
      'Real-time suggestions',
      'Brand voice consistency',
      'Plagiarism detection'
    ],
    cons: [
      'Can be overly prescriptive',
      "Doesn't understand all context",
      'Subscription per user adds up',
      'Not designed for financial/technical work'
    ],
    affiliateLink: '#',
    bestFor: 'Teams that write client-facing content and need polished communication',
    recommendationPriority: 4 // Lower priority - only for writing-heavy roles
  },

  // ==================== PRODUCTIVITY & AUTOMATION ====================
  {
    id: 'zapier-ai',
    name: 'Zapier AI',
    description: 'Workflow automation platform that connects apps and automates repetitive tasks',
    category: ['Automation', 'Integration'],
    industries: ['all'],
    useCases: ['workflow-automation', 'data-entry', 'integration'],
    roleRelevance: {
      primary: ['operations', 'entrepreneur', 'accounting', 'sales_rep'],
      secondary: ['all'],
      notRecommendedFor: []
    },
    taskMatch: {
      solves: ['automation', 'data_entry', 'workflow_automation', 'integration', 'repetitive_tasks'],
      doesNotSolve: ['complex_analysis', 'design', 'content_creation']
    },
    pricing: {
      tier: 'mid',
      range: '$20-600/month',
      model: 'Based on tasks/month'
    },
    techLevel: 2,
    companySize: ['solo', 'small', 'medium', 'large'],
    integrations: ['6000+ apps'],
    pros: [
      'Connects virtually any app',
      'No coding required',
      'Huge template library',
      'AI-powered automation suggestions'
    ],
    cons: [
      'Can get expensive with heavy use',
      'Troubleshooting can be tricky',
      'Complex workflows need planning'
    ],
    affiliateLink: '#',
    bestFor: 'Businesses with repetitive tasks across multiple tools',
    recommendationPriority: 7
  },

  // ==================== OTHER SOLUTIONS (with proper matching) ====================
  // [Include other solutions from your original file, but add the new metadata]
  // I'll show a few more examples of proper categorization...

  {
    id: 'jasper',
    name: 'Jasper AI',
    description: 'AI content creation platform for marketing copy, blog posts, and social media',
    category: ['Content Creation', 'Marketing'],
    industries: ['marketing', 'consulting', 'services'],
    useCases: ['content-creation', 'marketing', 'social-media'],
    roleRelevance: {
      primary: ['marketer', 'content_creator', 'social_media_manager'],
      secondary: ['consultant', 'entrepreneur'],
      notRecommendedFor: ['accounting', 'financial_analysis', 'developer', 'data_scientist']
    },
    taskMatch: {
      solves: ['content_creation', 'marketing', 'social_media', 'writing_speed', 'ideas'],
      doesNotSolve: [
        'reconciliations', 'financial_statements', 'coding', 'data_analysis',
        'bookkeeping', 'excel_complex'
      ]
    },
    pricing: {
      tier: 'mid',
      range: '$49-125/month',
      model: 'Per user subscription'
    },
    techLevel: 1,
    companySize: ['solo', 'small', 'medium'],
    integrations: ['Chrome extension', 'Surfer SEO', 'Grammarly'],
    pros: [
      'Built specifically for marketing',
      'Templates for common content types',
      'Brand voice training',
      'SEO optimization features'
    ],
    cons: [
      'Expensive for solo users',
      'Still needs human editing',
      'Learning curve for best results',
      'Not suitable for technical/financial work'
    ],
    affiliateLink: '#',
    bestFor: 'Marketing teams needing consistent content output',
    recommendationPriority: 2 // Very low for accounting
  },

  // ... Continue with other solutions, ensuring each has proper roleRelevance and taskMatch
]
