// Code Generated by Sidekick is for learning and experimentation purposes only.
export interface AITool {
  id: string;
  name: string;
  category: string;
  description: string;
  strengths: string[];
  useCases: string[];
  bestFor: string[];
  pricing: string;
  link: string;
  industries: string[];
  roles: string[];
  
  // NEW: Smart matching metadata
  roleMatch: {
    // Roles where this is a PRIMARY recommendation (score: 10)
    primary: string[];
    // Roles where this is USEFUL but not primary (score: 5)
    secondary: string[];
    // Roles where this should NOT be recommended (score: 0)
    exclude?: string[];
  };
  
  taskMatch: {
    // Specific pain points from questionFlows this solves well
    strongMatch: string[];
    // Pain points this helps with but isn't perfect for
    weakMatch: string[];
    // Pain points this is NOT suited for
    noMatch?: string[];
  };
  
  // Priority for recommendation algorithm (1-10)
  recommendPriority: number;
}

export const AI_TOOLS: AITool[] = [
  // ==================== ACCOUNTING & FINANCE SPECIFIC ====================
  {
    id: 'excel-formula-bot',
    name: 'Excel Formula Bot',
    category: 'Spreadsheet AI',
    description: 'AI that writes Excel formulas, explains complex spreadsheets, and generates VBA code from plain English descriptions.',
    strengths: ['Excel formula generation', 'VBA coding', 'Formula explanation', 'Google Sheets support', 'Fast'],
    useCases: ['excel_formulas', 'data_analysis', 'financial_modeling', 'automation'],
    bestFor: ['Excel power users', 'Financial analysts', 'Accountants', 'Data analysts'],
    pricing: '$7-10/mo',
    link: 'https://excelformulabot.com',
    industries: ['finance', 'accounting', 'consulting', 'all'],
    roles: ['accounting', 'financial_analyst', 'analyst', 'consultant', 'operations'],
    roleMatch: {
      primary: ['accounting', 'financial_analyst', 'analyst', 'consultant'],
      secondary: ['operations', 'entrepreneur', 'manager'],
      exclude: ['designer', 'content_creator', 'video_editor', 'marketer']
    },
    taskMatch: {
      strongMatch: ['excel_complex', 'complex_models', 'financial_modeling', 'data_analysis', 'automation'],
      weakMatch: ['report_writing'],
      noMatch: ['content_creation', 'design', 'video_editing', 'reconciliations']
    },
    recommendPriority: 10
  },
  {
    id: 'sheet-plus-ai',
    name: 'SheetPlus AI',
    category: 'Spreadsheet AI',
    description: 'AI assistant for Google Sheets and Excel that generates formulas, creates charts, and analyzes data through natural language.',
    strengths: ['Formula generation', 'Chart creation', 'Data analysis', 'Natural language', 'Multi-platform'],
    useCases: ['excel_formulas', 'data_analysis', 'visualization', 'reporting'],
    bestFor: ['Spreadsheet automation', 'Data analysis', 'Financial reporting', 'Quick charts'],
    pricing: '$5-15/mo',
    link: 'https://sheetplus.ai',
    industries: ['finance', 'accounting', 'consulting', 'all'],
    roles: ['accounting', 'financial_analyst', 'analyst', 'operations'],
    roleMatch: {
      primary: ['accounting', 'financial_analyst', 'analyst'],
      secondary: ['consultant', 'operations', 'entrepreneur'],
      exclude: ['designer', 'content_creator', 'developer']
    },
    taskMatch: {
      strongMatch: ['excel_complex', 'data_analysis', 'visualization', 'financial_modeling'],
      weakMatch: ['report_writing'],
      noMatch: ['reconciliations', 'bookkeeping', 'content_creation']
    },
    recommendPriority: 10
  },

  // ==================== GENERAL PURPOSE AI (STRATEGIC PLACEMENT) ====================
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    category: 'General AI Assistant',
    description: 'Versatile conversational AI for writing, analysis, coding, brainstorming, and general problem-solving across any domain.',
    strengths: ['Natural conversation', 'Wide knowledge base', 'Code generation', 'Writing assistance', 'Problem solving', 'Excel help'],
    useCases: ['content_creation', 'code_generation', 'research', 'data_analysis', 'customer_support', 'excel_formulas'],
    bestFor: ['General purpose tasks', 'Writing and editing', 'Quick research', 'Brainstorming', 'Excel formulas'],
    pricing: 'Free / $20/mo Pro',
    link: 'https://chat.openai.com',
    industries: ['all'],
    roles: ['all'],
    roleMatch: {
      primary: ['all'], // Universal tool
      secondary: [],
      exclude: []
    },
    taskMatch: {
      strongMatch: [
        'excel_complex', 'research', 'data_analysis', 'report_writing',
        'client_updates', 'email_writing', 'documentation', 'brainstorming'
      ],
      weakMatch: ['coding', 'design'],
      noMatch: ['automated_bookkeeping'] // Can't replace specialized automation
    },
    recommendPriority: 9
  },
  {
    id: 'claude',
    name: 'Claude',
    category: 'General AI Assistant',
    description: 'Advanced AI assistant by Anthropic, excelling at nuanced analysis, long-form content, and complex reasoning tasks.',
    strengths: ['Long context window', 'Nuanced analysis', 'Strong reasoning', 'Safety-focused', 'Code review', 'Document analysis'],
    useCases: ['content_creation', 'code_generation', 'research', 'data_analysis', 'document_review'],
    bestFor: ['Complex analysis', 'Long documents', 'Detailed reasoning', 'Code review', 'Financial analysis'],
    pricing: 'Free / $20/mo Pro',
    link: 'https://claude.ai',
    industries: ['all'],
    roles: ['all'],
    roleMatch: {
      primary: ['all'],
      secondary: [],
      exclude: []
    },
    taskMatch: {
      strongMatch: [
        'excel_complex', 'data_analysis', 'research', 'document_review',
        'variance_analysis', 'report_writing', 'complex_analysis'
      ],
      weakMatch: ['content_creation'],
      noMatch: ['automated_bookkeeping', 'design']
    },
    recommendPriority: 9
  },

  // ==================== WRITING TOOLS (LIMITED APPLICABILITY FOR ACCOUNTING) ====================
  {
    id: 'grammarly',
    name: 'Grammarly',
    category: 'Writing Assistant',
    description: 'AI-powered writing assistant for grammar, clarity, tone, and style across all your writing.',
    strengths: ['Real-time editing', 'Tone detection', 'Browser integration', 'Plagiarism check', 'Style guide'],
    useCases: ['content_creation', 'email_management', 'document_editing', 'professional_communication'],
    bestFor: ['Professional writing', 'Email communication', 'Document editing', 'Client reports'],
    pricing: 'Free / $12/mo Premium',
    link: 'https://grammarly.com',
    industries: ['all'],
    roles: ['all'],
    roleMatch: {
      primary: ['content_creator', 'marketer', 'attorney', 'consultant', 'executive'],
      secondary: ['all'], // Can be useful for anyone who writes
      exclude: [] // But NOT prioritized for technical roles
    },
    taskMatch: {
      strongMatch: ['report_formatting', 'client_updates', 'email_writing', 'documentation'],
      weakMatch: ['content_creation'],
      noMatch: [
        'reconciliations', 'journal_entries', 'financial_statements',
        'excel_complex', 'data_analysis', 'bookkeeping', 'coding'
      ]
    },
    recommendPriority: 3 // LOW priority for accounting - only if they have writing-heavy role
  },

  // ==================== ACCOUNTING SOFTWARE WITH AI ====================
  {
    id: 'quickbooks-ai',
    name: 'QuickBooks Online',
    category: 'Accounting Software',
    description: 'Leading accounting platform with AI features for transaction categorization, invoice matching, and cash flow insights.',
    strengths: ['Bank reconciliation', 'Auto-categorization', 'Invoice management', 'Financial reports', 'Mobile app'],
    useCases: ['bookkeeping', 'financial_reporting', 'invoicing', 'expense_tracking'],
    bestFor: ['Small business accounting', 'Bookkeeping', 'Financial statements', 'Tax prep'],
    pricing: '$30-200/mo',
    link: 'https://quickbooks.intuit.com',
    industries: ['accounting', 'all'],
    roles: ['accounting', 'bookkeeper', 'entrepreneur', 'financial_analyst'],
    roleMatch: {
      primary: ['accounting', 'bookkeeper', 'entrepreneur'],
      secondary: ['financial_analyst', 'operations'],
      exclude: ['developer', 'designer', 'marketer', 'content_creator']
    },
    taskMatch: {
      strongMatch: [
        'bookkeeping', 'reconciliations', 'journal_entries',
        'financial_statements', 'period_close', 'audit_prep'
      ],
      weakMatch: ['variance_analysis'],
      noMatch: ['content_creation', 'design', 'coding', 'marketing']
    },
    recommendPriority: 10
  },
  {
    id: 'xero-ai',
    name: 'Xero',
    category: 'Accounting Software',
    description: 'Cloud accounting with AI-powered bank feeds, reconciliation suggestions, and cash flow forecasting.',
    strengths: ['Bank reconciliation', 'Invoicing', 'Expense claims', 'Inventory', 'Beautiful UI'],
    useCases: ['bookkeeping', 'financial_reporting', 'invoicing', 'inventory_management'],
    bestFor: ['Cloud-first accounting', 'Multi-currency', 'Bank reconciliation', 'Modern businesses'],
    pricing: '$13-70/mo',
    link: 'https://xero.com',
    industries: ['accounting', 'all'],
    roles: ['accounting', 'bookkeeper', 'entrepreneur'],
    roleMatch: {
      primary: ['accounting', 'bookkeeper', 'entrepreneur'],
      secondary: ['financial_analyst'],
      exclude: ['developer', 'designer', 'marketer']
    },
    taskMatch: {
      strongMatch: ['bookkeeping', 'reconciliations', 'financial_statements', 'invoicing'],
      weakMatch: ['variance_analysis'],
      noMatch: ['content_creation', 'coding', 'marketing']
    },
    recommendPriority: 10
  },

  // ==================== CODING TOOLS (HIGH PRIORITY FOR DEVELOPERS ONLY) ====================
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    category: 'Code Assistant',
    description: 'AI pair programmer that suggests code completions, generates functions, and helps debug within your IDE.',
    strengths: ['IDE integration', 'Context-aware', 'Multiple languages', 'Real-time suggestions', 'Code explanation'],
    useCases: ['code_generation', 'debugging', 'code_review', 'learning'],
    bestFor: ['Software developers', 'Code completion', 'Learning new languages', 'Rapid prototyping'],
    pricing: '$10/mo',
    link: 'https://github.com/features/copilot',
    industries: ['technology', 'finance', 'healthcare', 'all'],
    roles: ['software_developer', 'data_scientist', 'engineer'],
    roleMatch: {
      primary: ['software_developer', 'data_scientist', 'engineer'],
      secondary: ['analyst'], // Only if they code
      exclude: ['accounting', 'bookkeeper', 'marketer', 'designer', 'content_creator']
    },
    taskMatch: {
      strongMatch: ['boilerplate', 'coding', 'debugging', 'refactoring', 'tests'],
      weakMatch: ['documentation'],
      noMatch: [
        'reconciliations', 'bookkeeping', 'financial_statements',
        'content_creation', 'marketing', 'design'
      ]
    },
    recommendPriority: 10
  },

  // ... Continue with other tools, ensuring proper matching metadata for each

  // ==================== MARKETING TOOLS (EXCLUDE FROM ACCOUNTING) ====================
  {
    id: 'jasper',
    name: 'Jasper AI',
    category: 'Content Creation',
    description: 'Enterprise-grade AI writing platform for marketing content, blog posts, social media, and brand-consistent copy.',
    strengths: ['Marketing focus', 'Brand voice', 'Templates', 'Team collaboration', 'SEO optimization'],
    useCases: ['content_creation', 'marketing', 'social_media', 'seo'],
    bestFor: ['Marketing teams', 'Content marketers', 'Brand storytelling', 'SEO content'],
    pricing: '$49/mo+',
    link: 'https://jasper.ai',
    industries: ['marketing', 'media', 'retail', 'technology'],
    roles: ['marketer', 'content_creator', 'social_media_manager'],
    roleMatch: {
      primary: ['marketer', 'content_creator', 'social_media_manager'],
      secondary: ['consultant', 'entrepreneur'],
      exclude: ['accounting', 'financial_analyst', 'bookkeeper', 'developer', 'data_scientist']
    },
    taskMatch: {
      strongMatch: ['content_creation', 'marketing', 'social_media', 'writing_speed', 'ideas'],
      weakMatch: [],
      noMatch: [
        'reconciliations', 'journal_entries', 'financial_statements',
        'excel_complex', 'bookkeeping', 'coding', 'data_analysis'
      ]
    },
    recommendPriority: 1 // Do NOT recommend to accounting
  },

  // ... Include rest of tools with proper metadata
]

export type AITool = typeof AI_TOOLS[number]
